### PR TITLE
Replace Alt.js with Redux and upgrade react-scripts

### PR DESCRIPTION
**Pull request by dlajarretie**
### Login / Sign up :
- ✅   Sign up
- ✅   Sign in without 2FA
- ✅   Sign in with 2FA
- ✅   Sign in with shortlogin

### Secret list :
- ✅   Display empty secret list
- ✅   Display home secret list
- ✅   Display "all" secret list
- ✅   Display "my" secret list
- ✅   Display "shared" secret list
- ✅   Display folders
- ✅   Navigate inside folders
- ✅   Breadcrumbs
- ✅   Delete folder
- ✅   Search folder
- ✅   Delete secret
- ✅   Search secret
- ✴️   Refresh secret list - Bug: First refresh reloads the previous state
- ✅   Drag-n-drop secret in folder
- ✅   Remove secret from folder
- ✅   Shared with
- ✅   Sort alphabetically

### Secret/Folder modal :
- ✅   Create secret
- ✅   Show secret
- ✅   Edit secret
- ✅   Share secret
- ✅   Unshare secret
- ✅   Update sharing permissions on secret
- ✅   Rename secret
- ✅   Generate password
- ✅   Create folder
- ✅   Show folder
- ✅   Share folder
- ✅   Unshare folder
- ✅   Update sharing permissions on folder
- ✅   Rename folder
- ✅   Create secret inside folder
- ✅   Create secret inside nested folder
- ✅   Create folder inside folder
- ✅   Create folder inside nested folder

### Import / Export :
- ✅   Export secrets
- ✅   Import secrets

### Settings :
- ✅   Enable 2FA
- ✅   Enable shortlogin
- ✅   Enable auto logout
- ✅   Change master password

## Already done :
- Did a naive rewrite of all Alt.js stores/actions using Redux Toolkit
- Got rid of Immutable.js (reducers use immer for immutability)
- Rewrote all components to connect them to the Redux store instead of Alt.js stores
- Fixed the dreaded bug of the latest user not appearing in the share list
- Fixed the also dreaded bug of cursor jumping to the end when editing input values

## Remaining tasks :
- Deploy to beta.secret-in.me

### CODE REVIEW

**Comment by agix** [comment]
Oh waow ! @Calyhre would be prode of you

**Comment by agix** [comment]
<3

**Comment by agix** [comment]
:man_dancing:

**Comment by dlajarretie** [comment]
Almost there 🥵

**Review by Calyhre — APPROVED** [review]
LGTM

**Review by agix — CHANGES_REQUESTED** [review]
Can you write better commit ?

:trollface:

**Pull request merged**
